package ch.ffhs.jee.model;

import java.io.Serializable;
import javax.persistence.*;


/**
 * The persistent class for the tTest database table.
 * 
 */
@Entity
@Table(name="tTest")
@NamedQuery(name="TestTable.findAll", query="SELECT t FROM TestTable t")
public class TestTable implements Serializable {
	private static final long serialVersionUID = 1L;

	@Id 
	@Column(name="tstkey")
	private Long key;

	@Column(name="tstValue") 
	private String value;

	public TestTable() {
	}

	public Long getKey() {
		return this.key;
	}

	// key generated by sequence linked to the table (directly in the database)
	// public void setKey(Long key) {
	//	 this.key = key;
	// }

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}